name: Terraform-dev-Deploy

on:
    push:
        branches:
            - dev
    pull_request:

jobs:
    terraform:
        runs-on: ubuntu-latest

        # Add permissions for WIF
        permissions:
            contents: "read"
            id-token: "write"

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                  terraform_version: 1.8.5

            # This is the new, recommended authentication step
            - name: Authenticate to Google Cloud
              id: auth
              uses: "google-github-actions/auth@v2"
              with:
                  # You must create these secrets in your GitHub repository
                  workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
                  service_account: ${{ secrets.GCP_SA_EMAIL }}
                  audience: ${{ secrets.GCP_AUDIENCE }}

            # You no longer need the gcp-key.json, head, or jq steps

            - name: Terraform Init
              run: terraform init
            # No 'env' block needed. Authentication is automatic.

            - name: Terraform Plan
              run: terraform plan -var-file="envs/dev.tfvars"
            # No 'env' block needed.

            # IMPORTANT: Fixed the 'if' condition to run on 'dev' branch
            - name: Terraform Apply
              if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
              run: terraform apply -auto-approve -var-file="envs/dev.tfvars"
            # No 'env' block needed.
