name: Terraform-dev-Deploy

on:
    push:
        branches:
            - dev
    pull_request:

jobs:
    terraform:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            id-token: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                  terraform_version: 1.8.5

            - name: Configure GCP credentials
              run: |
                  echo "$GCP_CREDENTIALS" | sed 's/n/\n/g' > gcp-key.json
              shell: bash

            - name: Verify credentials file format
              run: |
                  head -5 gcp-key.json

            - name: Terraform Init
              run: terraform init
              env:
                  GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp-key.json

            - name: Terraform Plan
              run: terraform plan -var-file="envs/dev.tfvars"
              env:
                  GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp-key.json

            - name: Terraform Apply
              if: github.ref == 'refs/heads/main'
              run: terraform apply -auto-approve -var-file="envs/dev.tfvars"
              env:
                  GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp-key.json
